export const POMODORO_SECONDS_DECREMENT = 'POMODORO_SECONDS_DECREMENT'
export const POMODORO_SECONDS_RESET = 'POMODORO_SECONDS_RESET'

export const REST_SECONDS_DECREMENT = 'REST_SECONDS_DECREMENT'
export const REST_SECONDS_RESET = 'REST_SECONDS_RESET'

export const POMODORO_MINUTES_INCREMENT = 'POMODORO_MINUTES_INCREMENT'
export const POMODORO_MINUTES_DECREMENT = 'POMODORO_MINUTES_DECREMENT'

export const REST_MINUTES_INCREMENT = 'REST_MINUTES_INCREMENT'
export const REST_MINUTES_DECREMENT = 'REST_MINUTES_DECREMENT'

// export const POMODORO_DURATION_CHANGE_REQUEST =
//   'POMODORO_DURATION_CHANGE_REQUEST'
// export const POMODORO_DURATION_CHANGE_SUCCESS =
//   'POMODORO_DURATION_CHANGE_SUCCESS'
// export const POMODORO_DURATION_CHANGE_FAIL = 'POMODORO_DURATION_CHANGE_FAIL'

// export const REST_DURATION_CHANGE_REQUEST = 'REST_DURATION_CHANGE_REQUEST'
// export const REST_DURATION_CHANGE_SUCCESS = 'REST_DURATION_CHANGE_SUCCESS'
// export const REST_DURATION_CHANGE_FAIL = 'REST_DURATION_CHANGE_FAIL'

export const POMODORO_GET_REQUEST = 'POMODORO_GET_REQUEST'
export const POMODORO_GET_SUCCESS = 'POMODORO_GET_SUCCESS'
export const POMODORO_GET_FAIL = 'POMODORO_GET_FAIL'

export const POMODORO_CREATE_REQUEST = 'POMODORO_CREATE_REQUEST'
export const POMODORO_CREATE_SUCCESS = 'POMODORO_CREATE_SUCCESS'
export const POMODORO_CREATE_FAIL = 'POMODORO_CREATE_FAIL'
export const POMODORO_CREATE_RESET = 'POMODORO_CREATE_RESET'

export const POMODORO_DURATION_CHANGE = 'POMODORO_DURATION_CHANGE'
export const POMODORO_DURATION_RESET = 'POMODORO_DURATION_RESET'
export const REST_DURATION_CHANGE = 'REST_DURATION_CHANGE'
export const REST_DURATION_RESET = 'REST_DURATION_RESET'
