export const POMODORO_GET_REQUEST = 'POMODORO_GET_REQUEST'
export const POMODORO_GET_SUCCESS = 'POMODORO_GET_SUCCESS'
export const POMODORO_GET_FAIL = 'POMODORO_GET_FAIL'

export const POMODORO_CREATE_REQUEST = 'POMODORO_CREATE_REQUEST'
export const POMODORO_CREATE_SUCCESS = 'POMODORO_CREATE_SUCCESS'
export const POMODORO_CREATE_FAIL = 'POMODORO_CREATE_FAIL'
export const POMODORO_CREATE_RESET = 'POMODORO_CREATE_RESET'
