export const POMODORO_DONE_CREATE_REQUEST = 'POMODORO_DONE_CREATE_REQUEST'
export const POMODORO_DONE_CREATE_SUCCESS = 'POMODORO_DONE_CREATE_SUCCESS'
export const POMODORO_DONE_CREATE_FAIL = 'POMODORO_DONE_CREATE_FAIL'

export const POMODORO_DONE_GET_REQUEST = 'POMODORO_DONE_GET_REQUEST'
export const POMODORO_DONE_GET_SUCCESS = 'POMODORO_DONE_GET_SUCCESS'
export const POMODORO_DONE_GET_FAIL = 'POMODORO_DONE_GET_FAIL'
export const POMODORO_DONE_GET_RESET = 'POMODORO_DONE_GET_RESET'
